/*
* generated by Xtext
*/
package de.ubt.ai1.supermod.oel;


/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class OptionLangStandaloneSetup extends OptionLangStandaloneSetupGenerated{

	public static void doSetup() {
		new OptionLangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

