/*
 * generated by Xtext
 */
package de.ubt.ai1.supermod.oel;

import org.eclipse.xtext.linking.ILinker;
import org.eclipse.xtext.linking.impl.Linker;
import org.eclipse.xtext.scoping.IScopeProvider;

import de.ubt.ai1.supermod.oel.scoping.OptionLangScopeProvider;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class OptionLangRuntimeModule extends de.ubt.ai1.supermod.oel.AbstractOptionLangRuntimeModule {

	@Override
	public Class<? extends IScopeProvider> bindIScopeProvider() {
		return OptionLangScopeProvider.class;
	}
	
	@Override
	public Class<? extends ILinker> bindILinker() {
		return Linker.class;
	}
}
