/*
 * generated by Xtext
 */
package de.ubt.ai1.supermod.text.scoping

import de.ubt.ai1.supermod.oel.scoping.OptionLangScopeProvider

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 *
 */
class LogicalScopeProvider extends OptionLangScopeProvider {

}
