/*
 * generated by Xtext
 */
package de.ubt.ai1.supermod.text.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LogicalUiModule extends de.ubt.ai1.supermod.text.ui.AbstractLogicalUiModule {
	public LogicalUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
