/*
 * generated by Xtext
 */
package de.ubt.ai1.supermod.oel.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.ubt.ai1.supermod.oel.services.OptionLangGrammarAccess;

public class OptionLangParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private OptionLangGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS");
	}
	
	@Override
	protected de.ubt.ai1.supermod.oel.parser.antlr.internal.InternalOptionLangParser createParser(XtextTokenStream stream) {
		return new de.ubt.ai1.supermod.oel.parser.antlr.internal.InternalOptionLangParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "OptionExpr";
	}
	
	public OptionLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(OptionLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
