/*
 * generated by Xtext
 */
package de.ubt.ai1.supermod.text.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.ubt.ai1.supermod.text.services.LogicalGrammarAccess;

public class LogicalParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private LogicalGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS");
	}
	
	@Override
	protected de.ubt.ai1.supermod.text.parser.antlr.internal.InternalLogicalParser createParser(XtextTokenStream stream) {
		return new de.ubt.ai1.supermod.text.parser.antlr.internal.InternalLogicalParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "LogicalDimension";
	}
	
	public LogicalGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LogicalGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
