/*
 * generated by Xtext
 */
package de.ubt.ai1.supermod.text.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LogicalAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/ubt/ai1/supermod/text/parser/antlr/internal/InternalLogical.tokens");
	}
}
