<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="textfile" nsURI="http://ai1.uni-bayreuth.de/supermod/textfile/0.1.0"
    nsPrefix="de.ubt.ai1.supermod.mm.textfile">
  <eClassifiers xsi:type="ecore:EClass" name="TextFileContent" eSuperTypes="../../de.ubt.ai1.supermod.mm.file/model/SuperModFile.ecore#//VersionedFileContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lines" upperBound="-1"
        eType="#//TextLine" containment="true" eOpposite="#//TextLine/textFileContent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lineOrdering" eType="ecore:EClass ../../de.ubt.ai1.supermod.mm.list/model/SuperModList.ecore#//VersionedList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextLine" eSuperTypes="../../de.ubt.ai1.supermod.mm.core/model/SuperModCore.ecore#//ProductSpaceElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textFileContent" eType="#//TextFileContent"
        eOpposite="#//TextFileContent/lines"/>
  </eClassifiers>
</ecore:EPackage>
