/*
 * generated by Xtext
 */
package de.ubt.ai1.supermod.oel.scoping

import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it 
 *
 */
class OptionLangScopeProvider extends AbstractDeclarativeScopeProvider {

}
