/*
 * generated by Xtext
 */
package de.ubt.ai1.supermod.text.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.ubt.ai1.supermod.text.ui.internal.LogicalActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LogicalExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LogicalActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LogicalActivator.getInstance().getInjector(LogicalActivator.DE_UBT_AI1_SUPERMOD_TEXT_LOGICAL);
	}
	
}
