<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="file" nsURI="http://ai1.uni-bayreuth.de/supermod/file/0.1.0"
    nsPrefix="de.ubt.ai1.supermod.mm.file">
  <eClassifiers xsi:type="ecore:EClass" name="VersionedFileSystem" eSuperTypes="../../de.ubt.ai1.supermod.mm.core/model/SuperModCore.ecore#//ProductDimension">
    <eOperations name="getResource" eType="#//VersionedResource">
      <eParameters name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="createFile" eType="#//VersionedFile">
      <eParameters name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="createFolder" eType="#//VersionedFolder">
      <eParameters name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roots" upperBound="-1"
        eType="#//VersionedResource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allResources" upperBound="-1"
        eType="#//VersionedResource" changeable="false" volatile="true" transient="true"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VersionedResource" abstract="true" eSuperTypes="../../de.ubt.ai1.supermod.mm.core/model/SuperModCore.ecore#//ProductSpaceElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//VersionedFolder"
        eOpposite="#//VersionedFolder/contents"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VersionedFolder" eSuperTypes="#//VersionedResource">
    <eOperations name="getContent" eType="#//VersionedResource">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//VersionedResource" containment="true" eOpposite="#//VersionedResource/container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allContents" upperBound="-1"
        eType="#//VersionedResource" changeable="false" volatile="true" transient="true"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VersionedFile" eSuperTypes="#//VersionedResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//VersionedFileContent"
        eOpposite="#//VersionedFileContent/file"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VersionedFileContent" abstract="true"
      eSuperTypes="../../de.ubt.ai1.supermod.mm.core/model/SuperModCore.ecore#//ProductSpaceElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="file" eType="#//VersionedFile"
        eOpposite="#//VersionedFile/content"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="superExtension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
</ecore:EPackage>
