<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="client" nsURI="http://ai1.uni-bayreuth.de/supermod/textfile/client/0.1.0"
    nsPrefix="de.ubt.ai1.supermod.mm.textfile.client">
  <eClassifiers xsi:type="ecore:EClass" name="TextFileExportTrace" eSuperTypes="../../de.ubt.ai1.supermod.mm.file.client/model/SuperModFileClient.ecore#//VersionedFileExportTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lines" upperBound="-1"
        eType="#//TextLineExportTrace" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextLineExportTrace">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineNr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="line" eType="ecore:EClass ../../de.ubt.ai1.supermod.mm.textfile/model/SuperModTextfile.ecore#//TextLine"/>
  </eClassifiers>
</ecore:EPackage>
