<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="client" nsURI="http://ai1.uni-bayreuth.de/supermod/emffile/client/0.1.0"
    nsPrefix="de.ubt.ai1.supermod.mm.emffile.client">
  <eClassifiers xsi:type="ecore:EClass" name="EMFObjectClassConflict" eSuperTypes="../../de.ubt.ai1.supermod.mm.client/model/SuperModClient.ecore#//ProductConflict">
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedObject" eType="ecore:EClass ../../de.ubt.ai1.supermod.mm.emffile/model/SuperModEMFFile.ecore#//EMFObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMFClassDefinitionConflict" eSuperTypes="../../de.ubt.ai1.supermod.mm.client/model/SuperModClient.ecore#//ProductConflict">
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedClassRef" eType="ecore:EClass ../../de.ubt.ai1.supermod.mm.emffile/model/SuperModEMFFile.ecore#//EMFClassRef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMFFeatureCompatibilityConflict" eSuperTypes="../../de.ubt.ai1.supermod.mm.client/model/SuperModClient.ecore#//ProductConflict">
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedFeatureRef" eType="ecore:EClass ../../de.ubt.ai1.supermod.mm.emffile/model/SuperModEMFFile.ecore#//EMFFeatureRef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMFObjectContainerConflict" eSuperTypes="../../de.ubt.ai1.supermod.mm.client/model/SuperModClient.ecore#//ProductConflict">
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedObject" eType="ecore:EClass ../../de.ubt.ai1.supermod.mm.emffile/model/SuperModEMFFile.ecore#//EMFObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMFCyclicContainmentConflict" eSuperTypes="../../de.ubt.ai1.supermod.mm.client/model/SuperModClient.ecore#//ProductConflict">
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedObjects" upperBound="-1"
        eType="ecore:EClass ../../de.ubt.ai1.supermod.mm.emffile/model/SuperModEMFFile.ecore#//EMFObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMFSingleFeatureValueConflict" eSuperTypes="../../de.ubt.ai1.supermod.mm.client/model/SuperModClient.ecore#//ProductConflict">
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedFeatureRef" eType="ecore:EClass ../../de.ubt.ai1.supermod.mm.emffile/model/SuperModEMFFile.ecore#//EMFFeatureRef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMFMultiFeatureValueConflict" eSuperTypes="../../de.ubt.ai1.supermod.mm.client/model/SuperModClient.ecore#//ProductConflict">
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedFeatureRef" eType="ecore:EClass ../../de.ubt.ai1.supermod.mm.emffile/model/SuperModEMFFile.ecore#//EMFFeatureRef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMFLinkCompatibilityConflict" eSuperTypes="../../de.ubt.ai1.supermod.mm.client/model/SuperModClient.ecore#//ProductConflict">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incompatibleLink" eType="ecore:EClass ../../de.ubt.ai1.supermod.mm.emffile/model/SuperModEMFFile.ecore#//EMFInternalReferenceValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMFObjectDefinitionConflict" eSuperTypes="../../de.ubt.ai1.supermod.mm.client/model/SuperModClient.ecore#//ProductConflict">
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedObjectRef" eType="ecore:EClass ../../de.ubt.ai1.supermod.mm.emffile/model/SuperModEMFFile.ecore#//EMFExternalReferenceValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMFReferentialIntegrityConflict" eSuperTypes="../../de.ubt.ai1.supermod.mm.client/model/SuperModClient.ecore#//ProductConflict">
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedObjectRef" eType="ecore:EClass ../../de.ubt.ai1.supermod.mm.emffile/model/SuperModEMFFile.ecore#//EMFInternalReferenceValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMFFileExportTrace" eSuperTypes="../../de.ubt.ai1.supermod.mm.file.client/model/SuperModFileClient.ecore#//VersionedFileExportTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="emfObjectToEObjectMap"
        upperBound="-1" eType="#//EMFObjectToEObjectMapEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMFObjectToEObjectMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="ecore:EClass ../../de.ubt.ai1.supermod.mm.emffile/model/SuperModEMFFile.ecore#//EMFObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
</ecore:EPackage>
